#!/usr/bin/env bash
############################


SCRIPT="${0}"
SCRIPT_NAME=$(basename "${SCRIPT}")

if [[ "$#" == "0" ]] ; then
	_die "USAGE: ni-delete-all [files to purge from context]"
fi

if [[ "${NI_CONTEXT_DIR}" == "" ]] ; then
        _die "NI_CONTEXT_DIR undefined!!! You must use a context using the use command to define it" 
fi

for FILE in "$@" ; do
	if echo "$FILE" | egrep -iq "^CK[-].*$" ; then 
		find "${NI_CONTEXT_DIR}/" -name "${FILE}" -print  | while read it ; do
			REALFILE=`readlink -f "$it"`
			if ! [[ -d "${REALFILE}" ]] ; then
				_info "Deleting ${it}"
				rm -f "${it}"
			fi
		done
	else
		_warn "Won't delete ${FILE} because it has not been ingested."
	fi
done

FILENAMES_DIR="${NI_CONTEXT_DIR}/.meta/FILENAMES"
# prune empty ones.
find "${FILENAMES_DIR}" -type d -empty -print | while read EMPTY
do
	_info "Deleting empty directory $EMPTY"
	rmdir "$EMPTY"
done

