#!/usr/bin/env bash
#############################

##################
# Script: get-name
#
# Purpose get the original filenames of the files you've ingested. ( we weren;t storing that but now ingest does )
# Usage: ni-cmd get-name file
# 


if [[ "${NI_CONTEXT_DIR}" == "" ]] ; then
	_die "NI_CONTEXT_DIR undefined!!! You must use a context using the use command to define it" 
fi


if [[ ! -d "${NI_CONTEXT_DIR}" ]] ; then
        _info "${NI_CONTEXT_DIR} did not exist, creating it" 
        mkdir -p "${NI_CONTEXT_DIR}"
        if [[ "$?" != "0" ]] ; then
                _die "Could not create NI_CONTEXT_DIR: $NI_CONTEXT_DIR because mkdir -p returned $?"
        fi
fi

META_DIR="${NI_CONTEXT_DIR}/.meta"
if [[ ! -d "${META_DIR}" ]] ; then
        echo "${META_DIR} did not exist, creating it" >&2
        mkdir -p "${META_DIR}"
        if [[ "$?" != "0" ]] ; then
                _die "Could not create META_DIR: $META_DIR because mkdir -p returned $?"
        fi
fi

FILENAME="${1}"
REST="${2}"

if [[ -z "${FILENAME}" ]] ; then
	_die "Usage: ni-cmd get-name file"
fi

if ! [[ -z "${REST}" ]] ; then
	_die "Usage: ni-cmd get-name file"
fi

if [[ ! -e "${FILENAME}" ]] ; then
	FBN=$(basename ${FILENAME})
	ALL_FILENAME="${NI_CONTEXT_DIR}/All/${FBN}"
	if [[ ! -e "${ALL_FILENAME}" ]] ; then
		_die "${FILENAME} did not exist and neither did ${ALL_FILENAME}." 
	else 
		# >&2 echo "WARNING ${FILENAME} did not exist checking ${ALL_FILENAME}." 
		FILENAME="${ALL_FILENAME}"
	fi
fi

if [[ ! -f "${FILENAME}" ]] ; then
	_die "${FILENAME} was not a file." >&2
fi


FILEDIR=$(dirname "${FILENAME}")
FILEBASENAME=$(basename "${FILENAME}")


FILENAME_DIR="${META_DIR}/FILENAMES"
if [[ ! -e "${FILENAME_DIR}" ]] ; then
	# in this case no files have names stored
	exit 0
fi

# we're doing one filename per file, but this could support multiple alternate filenames
IFS=$'\n'
for RESULT in $(find "${FILENAME_DIR}" -name "${FILEBASENAME}" -print) 
do
	PARENT_DIR=$(dirname "${RESULT}")
	ORIGINAL_FILENAME=$(basename "${PARENT_DIR}")
	echo "${ORIGINAL_FILENAME}"
done | sort | uniq
unset IFS

