#!/usr/bin/env bash
######################################

if [[ "${NI_CONTEXT_DIR}" == "" ]] ; then
	_die "NI_CONTEXT_DIR undefined!!! You must use a context using the use command to define it"
fi


if [[ ! -d "${NI_CONTEXT_DIR}" ]] ; then
        _info "${NI_CONTEXT_DIR} did not exist, creating it"
        mkdir -p "${NI_CONTEXT_DIR}"
        if [[ "$?" != "0" ]] ; then
                _die "Could not create NI_CONTEXT_DIR: $NI_CONTEXT_DIR because mkdir -p returned $?"
        fi
fi
# allow this to be overridden
if [[ "${ALL_TAG}" == "" ]] ; then
        ALL_TAG="All"
fi
ALL_DIR="${NI_CONTEXT_DIR}/${ALL_TAG}"
if [[ ! -d "${ALL_DIR}" ]] ; then
        _info "${ALL_DIR} did not exist, creating it" 
        mkdir -p "${ALL_DIR}"
        if [[ "$?" != "0" ]] ; then
        	_die "Could not create ALL_DIR: $ALL_DIR because mkdir -p returned $?"
        fi
fi

META_DIR="${NI_CONTEXT_DIR}/.meta"
if [[ ! -d "${META_DIR}" ]] ; then
        echo "${META_DIR} did not exist, creating it" >&2
        mkdir -p "${META_DIR}"
        if [[ "$?" != "0" ]] ; then
                _die "Could not create META_DIR: $META_DIR because mkdir -p returned $?"
        fi
fi


if [[ "$1" == "" ]] ; then
	_warn "What file did you want to see the tags for?"
	_die "USAGE: ni-inf file"
fi
LOOKFOR=$(basename "$1")
if [[ "$2" != "" ]] ; then
	_warn "Extra argument $2"
	_die "USAGE: ni-inf file"
fi

echo "UNIQUE_FILENAME: $LOOKFOR"
FILENAME_DIR="${META_DIR}/FILENAMES"
IFS=$'\n'
for FILE in $(find -L "${FILENAME_DIR}" -type f -name "$LOOKFOR" -print | sort | uniq) ; do
	FILE_DIRNAME=$(dirname "$FILE")
	echo "FILENAME: "$(basename "${FILE_DIRNAME}")
done 
unset IFS
echo
echo "CONTEXT: ${NI_CONTEXT_DIR}/"  "FILE: $LOOKFOR"   
echo "TAGS:"
echo "----------------------------"



IFS=$'\n'
for FILE in $(find -L "${NI_CONTEXT_DIR}/" \( -path ${META_DIR} -o -path ${ALL_DIR} \) -prune -o -type f -name "$LOOKFOR"   -print | sort | uniq) ; do
	FILE_DIRNAME=$(dirname "$FILE")
	echo "${FILE_DIRNAME#${NI_CONTEXT_DIR}/}"
done 
unset IFS




